# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d442858391a1d04ae98ba5c6b1487cfa59097b240341860fd37bb1fc53f9488f60a7c7500c1934d4152747d32697d88ac18dbda299a55fff3fc2665a3a4791d0

test:
  secret_key_base: 638a905d31968fa6971bb701642d26106146c0be2bbce2a90a4c88de8863e63c5f09bfafad92bfd1c0245bd4eb3b991b72c68b8d0f7a5e5f4de5e89fbe3fdf88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
